[package]
name = "actix-sse"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = { version = "4.4" }
actix-web-lab = { version = "0.18" }
parking_lot = { version = "0.12" }
futures-util = { version = "0.3", default-features = false, features = ["std"] }
chrono = "0.4.34"
